version: '3.1'

services:
  # nginx:
  #   image: nginx
  #   ports:
  #     - 8888:80

  server-info: 
    image: dwoof42/server-info:latest
    deploy:
      mode: global
    environment:
      - ASPNETCORE_URLS=http://*:4000
    networks:
      - stack

  rabbit1:
    image: rabbitmq:3-management
    ports:
      - 10000:15672
    networks:
      - stack
  rabbit2:
    image: rabbitmq:3-management
    ports:
      - 10001:15672
    networks:
      - stack
  rabbit3:
    image: rabbitmq:3-management
    ports:
      - 10002:15672
    networks:
      - stack

  proxy:
    image: dwoof42/nginx-proxy-sample:1.0.4
    ports:
      - 80:80
    networks:
      - stack
    deploy:
      replicas: 2

  visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - stack

networks:
  stack:
    external: true
