version: '3.7'

services:
  # nginx:
  #   image: nginx
  #   ports:
  #     - 8888:80

  server-info: 
    image: dwoof42/server-info:latest
    deploy:
      mode: global
    environment:
      - ASPNETCORE_URLS=http://*:4000
    ports:
      - 4000:4000
    networks:
      - stack

  server-info-client:
    image: dwoof42/server-info-client:latest
    environment:
      - PORT=5000
      - URL=http://server-info:4000/api/values
    networks:
      - stack

  rabbit1:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    deploy:
      placement:
        constraints:
          - node.labels.rabbit == rabbit
    volumes:
      - /var/lib/rabbitmq:/var/lib/rabbitmq
    networks:
      - stack

  proxy:
    image: dwoof42/nginx-proxy-sample:1.0.8
    ports:
      - 80:80
    networks:
      - stack
    deploy:
      replicas: 2

  visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - stack

  mongo:
    image: mongo
    ports: 
      - 27017:27017
  web:
    image: nginx
    ports: 
      - 81:81
    environment:
      - NGINX_PORT=81
    networks:
      - stack

  redis:
    image: redis
    networks:
      - stack


  counter-consumer:
    image: dwoof42/counter-consumer:1.0.1
    networks:
      - stack
    deploy:
      replicas: 2

  counter-producer:
    image: dwoof42/counter-producer:1.0.1
    networks:
      - stack

networks:
  stack:
    external: true
